status = [
    "build-and-test (1.38.0, false)",
    "build-and-test (stable, false)",
    "build-and-test (beta, false)",
    "build-and-test (stable, x86_64-unknown-linux-musl, false)",
    "test-on-docker (docker:19.03-dind)",
    "test-on-docker (docker:18.09-dind)",
    "test-on-docker (docker:18.06-dind)",
    "test-on-docker (docker:18.03-dind)",
    "test-on-docker (docker:17.12-dind)",
    "test-on-docker (docker:17.09-dind)",
    "test-on-docker (docker:17.07-dind)",
    "test-on-docker (docker:17.06-dind)",
    "test-on-docker (docker:1.13-dind)",
    "rustfmt",
    "clippy",
    "check-license-headers",
]
