status = [
    "build-and-test (1.38.0, false)",
    "build-and-test (stable, false)",
    "build-and-test (beta, false)",
    "build-and-test (stable, x86_64-unknown-linux-musl, false)",
    "rustfmt",
    "clippy",
]
